INSERT INTO CASH_CARD(ID , AMOUNT, OWNER) VALUES(99, 123.45, 'Jakaza')
INSERT INTO CASH_CARD(ID , AMOUNT,OWNER) VALUES(100, 150,  'Jakaza')
INSERT INTO CASH_CARD(ID , AMOUNT, OWNER) VALUES(101, 200,  'Jakaza')
INSERT INTO CASH_CARD(ID , AMOUNT, OWNER) VALUES(102, 2.00,  'Jakaza')